# Site settings
title: "Perfil Profesional"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Manuel Oswaldo Guevara Samaniego"
resume_title:                   "Pedagogy of Experimental Computer Sciences"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "https://drive.google.com/file/d/1lPxH0ba7yLCqctR6aVogOdZPMb16aFZB/view?usp=sharing"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+593 98 990 6448"
resume_contact_address:         "August 10 and Cuba"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>
Hello, my name is Manuel and I am 22 years old. <br>
I am a person with many virtues, among them I highlight my ability to work in a team, my perseverance to achieve my goals and my empathy towards others.
I consider myself a proactive person with a positive attitude towards the challenges that arise in my life.
As for my interests, I really like sports. I regularly practice Taekwondo and Soccer, which helps me keep fit and release the stress of everyday life.<br>
Sport has also taught me values such as respect, discipline and self-improvement.
</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "hhttps://github.com/oswa33"
  resume_twitter_url:           "https://twitter.com/ManuelG79753478?t=Co8zFwiSOLekPTxSBaWWxQ&s=09"
#  resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/oswaldo.guevara.54738?mibextid=ZbWKwL"
#  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  resume_instagram_url:         "https://www.instagram.com/manuel_oswaldo00/"
#  resume_website_url:           "http://joelglovier.com"
#  resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
